# Generated by Django 3.1 on 2020-08-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=60)),
                ('number_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=150)),
                ('release_date', models.DateField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BookAndAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal_books.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal_books.book')),
            ],
        ),
    ]
