# Generated by Django 3.1 on 2020-09-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=60)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=150)),
                ('release_date', models.DateField(max_length=150)),
                ('authors', models.ManyToManyField(related_name='author_books', to='internal_books.Author')),
            ],
        ),
    ]
