# Generated by Django 3.1 on 2020-08-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookandauthors',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal_books.author'),
        ),
        migrations.AlterField(
            model_name='bookandauthors',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='internal_books.book'),
        ),
    ]
