# Generated by Django 3.1 on 2020-08-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_books', '0002_auto_20200824_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='chic',
        ),
    ]
