# Generated by Django 3.1 on 2020-08-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_books', '0003_remove_author_chic'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='internal_books.book'),
        ),
        migrations.DeleteModel(
            name='BookAndAuthors',
        ),
    ]
